// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Zoomies.Data;

#nullable disable

namespace Zoomies.Migrations
{
    [DbContext(typeof(ZoomiesDbContext))]
    [Migration("20260504120000_AddWishlistItemsAndMyListings")]
    partial class AddWishlistItemsAndMyListings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // The current model is stored in ZoomiesDbContextModelSnapshot.
            // Keeping this file small makes the classroom project easier to read.
        }
    }
}
