// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Zoomies.Data;

#nullable disable

namespace Zoomies.Migrations
{
    [DbContext(typeof(ZoomiesDbContext))]
    [Migration("20260504123000_AddCarConditionAndDtos")]
    partial class AddCarConditionAndDtos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // The current model is stored in ZoomiesDbContextModelSnapshot.
            // This classroom project keeps designer files compact for readability.
        }
    }
}
